server:
  port: 80
spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/auto_payment_bot
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update


app:
  security:
    username: Admin
    password: 12563Aas@