package uz.pdp.apptelegrambotautopayment.enums;

public enum LangFields {
    BUTTON_LANGUAGE_UZBEK, BUTTON_LANGUAGE_RUSSIAN, BUTTON_LANGUAGE_ENGLISH, HELLO, EXCEPTION_LANGUAGE, SUCCESSFULLY_CHANGED_LANGUAGE, MY_CARD_TEXT, EMPTY_CARD_NUMBER_TEXT, PRESENT_CARD_NUMBER_TEXT, ADD_CARD_NUMBER_TEXT, CHANGE_CARD_NUMBER_TEXT, BUTTON_LANG_SETTINGS
}
